apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: direct-csi
commonAnnotations:
  direct.csi.min.io/authors: "MinIO, Inc."
  direct.csi.min.io/license: "AGPLv3"
  direct.csi.min.io/support: "https://subnet.min.io"
commonLabels:
  direct.csi.min.io/version: $(VERSION)

configMapGenerator:
- name: direct-csi-config
  env: resources/direct-csi.properties
generatorOptions:
  disableNameSuffixHash: true
  labels:
    generated-by: "kustomize"

resources:
  - resources/workloads.yaml
  - resources/ns.yaml
  - resources/rbac.yaml
  - resources/csi.min.io_storagetopologies.yaml

configurations:
 - resources/kustomizeconfig.yaml  
  
vars:
  - name: VERSION
    objref:
      name: direct-csi-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.VERSION
  - name: DRIVES
    objref:
      name: direct-csi-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.DIRECT_CSI_DRIVES
  - name: DRIVES_DIR
    objref:
      name: direct-csi-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.DIRECT_CSI_DRIVES_DIR
  - name: REPOSITORY_ORG
    objref:
      name: direct-csi-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.DIRECT_CSI_REPOSITORY_ORG
  - name: REPOSITORY_IMAGE
    objref:
      name: direct-csi-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.DIRECT_CSI_REPOSITORY_IMAGE
