apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jbod-csi-driver
commonAnnotations:
  jbod.csi.driver.min.io/authors: "Minio, Inc."
  jbod.csi.driver.min.io/license: "AGPL"
  jbod.csi.driver.min.io/support: "https://subnet.min.io"
commonLabels:
  jbod.csi.driver.min.io/version: $(VERSION)

configMapGenerator:
- name: jbod-csi-driver-config
  env: kustomize/jbod-csi-driver.properties
generatorOptions:
  disableNameSuffixHash: true
  labels:
    generated-by: "kustomize"

resources:
  - kustomize/deploy.yaml
  - kustomize/ns.yaml
  - kustomize/rbac.yaml

configurations:
 - kustomize/kustomizeconfig.yaml  
  
vars:
  - name: VERSION
    objref:
      name: jbod-csi-driver-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.VERSION
  - name: DRIVE_PATHS
    objref:
      name: jbod-csi-driver-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.JBOD_CSI_DRIVER_PATHS
  - name: COMMON_CONTAINER_ROOT
    objref:
      name: jbod-csi-driver-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.JBOD_CSI_DRIVER_COMMON_CONTAINER_ROOT
  - name: COMMON_HOST_ROOT
    objref:
      name: jbod-csi-driver-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.JBOD_CSI_DRIVER_COMMON_HOST_ROOT
  - name: REPOSITORY_ORG
    objref:
      name: jbod-csi-driver-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.JBOD_CSI_DRIVER_REPOSITORY_ORG
  - name: REPOSITORY_IMAGE
    objref:
      name: jbod-csi-driver-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.JBOD_CSI_DRIVER_REPOSITORY_IMAGE
