name: Build

on:
  push:
    branches: [v4.0]

  pull_request:
    branches: [v4.0]

# This ensures that previous jobs for the PR are canceled when the PR is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
          check-latest: true
      - name: Set environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          mkdir -p "$(go env GOPATH)/src/github.com/minio/"
          ln -s "$PWD" "$(go env GOPATH)/src/github.com/minio/directpv"
      - name: Build and test
        env:
          CGO_ENABLED: 0
        run: |
          ./build.sh
          go test -v ./...
      - uses: docker/setup-qemu-action@v3
      - name: Check Goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --skip=publish,sign --clean --snapshot
